---
# tasks file for roles/jenkins
- name: Add Jenkins Key
  become: yes
  apt_key:
    url: https://pkg.jenkins.io/debian/jenkins.io.key
    state: present

- name: Add Jenkins Repos
  become: yes
  apt_repository:
    repo: deb https://pkg.jenkins.io/debian-stable binary/
    state: present

- name: Install Java JDK 11
  become: yes
  apt:
    name: openjdk-11-jdk
    state: present
    force_apt_get: yes
    update_cache: yes

- name: Install Jenkins
  become: yes
  apt:
    name: jenkins
    state: present
    update_cache: yes
    force_apt_get: yes

- name: Add jenkins user to Docker group
  become: yes
  user:
    name: jenkins
    groups: docker
    append: yes
  notify:
    - Restart Jenkins
    - Enable Jenkins

- name: Install Jenkins Plugins
  become: yes
  with_items:
    - configuration-as-code
    - credentials
    - git
    - github
    - workflow-aggregator
    - authentication-tokens
    - docker-commons
    - docker-java-api
    - docker-plugin
    - docker-workflow
  get_url:
    timeout: 100
    url: "https://updates.jenkins-ci.org/latest/{{ item }}.hpi"
    dest: "/var/lib/jenkins/plugins/{{ item }}.jpi"
    owner: jenkins
    group: jenkins
    mode: "0644"
  notify:
    - Restart Jenkins

- name: Jenkins Config as Code
  template:
    src: jenkins.yml.j2
    dest: ~/jenkins.yml
    mode: "0755"

- name: Jenkins SSH Config
  become: yes
  file:
    path: /var/lib/jenkins/.ssh
    state: directory
    owner: jenkins
    group: jenkins
    mode: '0700'

- name: Jenkins SSH Config
  become: yes
  copy:
    content: |
      Host *
        StrictHostKeyChecking no
    dest: /var/lib/jenkins/.ssh/config
    owner: jenkins
    group: jenkins
    mode: "0400"

- name: Jenkins SSH Key
  become: yes
  copy: 
    src: /home/{{ user }}/.ssh/id_rsa.pub
    dest: /var/lib/jenkins/.ssh/
    owner: jenkins
    group: jenkins
    mode: 0644
    remote_src: yes

- name: Jenkins SSH Key
  become: yes
  copy: 
    src: /home/{{ user }}/.ssh/id_rsa
    dest: /var/lib/jenkins/.ssh/
    owner: jenkins
    group: jenkins
    mode: 0600
    remote_src: yes
