---
- name: Clean System
  apt:
    autoremove: yes
    force_apt_get: yes

- name: Upgrade System
  apt:
    upgrade: 'yes'
    update_cache: yes
    force_apt_get: yes

- name: Install Required Packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - python3
      - python3-pip
      - unzip
      - git
    state: present
    update_cache: yes
    force_apt_get: yes

- name: Check if NGROK is Installed
  stat:
    path: /usr/bin/ngrok
  register: ngrok

- name: Download NGROK
  get_url: 
    url: https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
    dest: "/home/{{ user }}/ngrok.zip"
  when: not ngrok.stat.exists

- name: Install NGROK
  become: yes
  unarchive:
    src: "/home/{{ user }}/ngrok.zip"
    dest: "/usr/bin/"
  when: not ngrok.stat.exists

- name: Cleanup 
  file:
    path: "/home/{{ user }}/ngrok.zip"
    state: absent
  when: not ngrok.stat.exists
